// Rutas de Golden Booking usadas en las pruebas (baseUrl en cypress.config.js).
export const ROUTES = {
  login: "/login",
  registro: "/register",
  recuperar: "/forgot",
  home: "/home",
  miPerfil: "/mi-perfil",
  contactos: "/contactos",
  misMensajes: "/mis-mensajes",
  mensajes: "/mensajes",
  usuarios: "/usuarios",
  usuariosCrear: "/usuarios-crear",
  reservasDeportivas: "/reservas-deportivas",
  misReservasDeporte: "/reservas-deportivas/mis-reservas",
  gestionarReservasD: "/reservas-deportivas/gestionar",
  espacios: "/reservas-deportivas/espacios",
  habitaciones: "/habitaciones",
  gestionarHabitaciones: "/habitaciones/gestionar",
  crearHabitacion: "/habitaciones/crear",
  tiposHabitacion: "/habitaciones/tipos",
  misReservasHotel: "/reservas-hoteleras/mis-reservas",
  gestionarReservasHotel: "/reservas-hoteleras/gestionar",
  recepcion: "/recepcion/nueva-reserva",
};
